spring:
  application:
    name: ReservaFit-Backend
azure:
  activedirectory:
    tenant-id: 569ca4b8-5e33-460a-8759-2bc12cb2b1e0
    client-id: f4a5103b-ae57-406d-85e1-eee64edbc4ac
    application-id-uri: api://f4a5103b-ae57-406d-85e1-eee64edbc4ac
    